[versions]
autoValue = "1.9"
thrifty = "3.0.0"

[libraries]

# Build + runtime dependencies
androidTools-agp = "com.android.tools.build:gradle:7.4.0-alpha05" # Note that updates here usually require updates to androidTools-repository
androidTools-r8 = "com.android.tools:r8:3.3.28"
androidTools-repository = "com.android.tools:repository:30.4.0-alpha05"
autoValue-processor = { module = "com.google.auto.value:auto-value", version.ref = "autoValue" }
autoValue-annotations = { module = "com.google.auto.value:auto-value-annotations", version.ref = "autoValue" }
commons-io = "commons-io:commons-io:2.10.0"
commons-lang = "org.apache.commons:commons-lang3:3.12.0"
gson = "com.google.code.gson:gson:2.9.0"
javassist = "org.javassist:javassist:3.29.0-GA"
thriftyRuntime = { module = "com.microsoft.thrifty:thrifty-runtime-jvm", version.ref = "thrifty" }

# Test dependenies
groovy = "org.codehaus.groovy:groovy-all:3.0.9"
spock = "org.spockframework:spock-core:2.1-groovy-3.0" # Don't forget to exclude groovy-all

[plugins]
mavenPublish = "com.vanniktech.maven.publish:0.20.0"
gradlePluginPublish = "com.gradle.plugin-publish:0.21.0"
thrifty = { id = "com.microsoft.thrifty", version.ref = "thrifty" }
versions = "com.github.ben-manes.versions:0.42.0"
